### ISSUE TITLE
接口估计更换了。。

### ISSUE THREAD

**Issue by matocool** [xunichanghuan/mimotion-run#1]
接口估计更换了。。

**Comment by zhangbo-sys** [comment]
昨天突然不能用了

**Comment by xunichanghuan** [comment]
屏蔽了天气接口，测试action自动运行，天气过两天修复

**Comment by lffw001** [comment]
大佬，多账户怎么设置

**Comment by zhangbo-sys** [comment]
现在还有什么办法可以用吗？

**Comment by zhangbo-sys** [comment]
> > 现在还有什么办法可以用吗？
> 
> 无，因为步数的问题，支付宝估计是为了避免发生类似的事情，直接清理掉了 ZeppLife 的功能接口，具体原因不明。微信依然可用。

有点悲催，主要就用支付宝，微信的倒不关心

**Comment by xunichanghuan** [comment]
已更新多账号，邮箱支持，请测试
