### ISSUE TITLE
KeyError: 'location'##[error***Process completed with exit code 1.

### ISSUE THREAD

**Issue by sundys** [xunichanghuan/mimotion-run#2]
直接fork主分支的,变量全部添加了,没有的项都填写NO,天气选项都关闭了, 运行就报错, 变量核对了几遍,没有错误的地方.运行就卡在这个地方.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 7.6 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 15.0 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 41.9 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.0.1-cp[38](https://github.com/sundys/XiaoMI-run/actions/runs/4267421320/jobs/7429008443#step:5:38)-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (195 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.4/195.4 kB 54.2 MB/s eta 0:00:00
Installing collected packages: charset-normalizer, urllib3, idna, certifi, requests
Successfully installed certifi-2022.12.7 charset-normalizer-3.0.1 idna-3.4 requests-2.28.2 urllib3-1.26.14
Traceback (most recent call last):
  File "main.py", line 140, in <module>
    print(MiMotion(check_item=_check_item).main())
  File "main.py", line 106, in main
    login_token, userid = self.login(user, password)
  File "main.py", line [39](https://github.com/sundys/XiaoMI-run/actions/runs/4267421320/jobs/7429008443#step:5:39), in login
    location = r1.headers["Location"***
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/requests/structures.py", line [52](https://github.com/sundys/XiaoMI-run/actions/runs/4267421320/jobs/7429008443#step:5:52), in __getitem__
    return self._store[key.lower()***[1***
KeyError: 'location'
##[error***Process completed with exit code 1.

**Comment by xunichanghuan** [comment]
重新fork代码有更新，只配置MIMOTION就可以

**Comment by sundys** [comment]
> 

刚又重新fork了一遍,只配置MIMOTION,开微信推送, 也是卡在这里, 全部变量打开也是卡在这里,奇怪了

**Comment by xunichanghuan** [comment]
手机号是否加了+86，重新fork代码，新增手机号校验自动增加“+86”字段

**Comment by sundys** [comment]
> 手机号是否加了+86，重新fork代码，新增手机号校验自动增加“+86”字段

手机号加了+86 , josn格式及变量及字符全部检查了一篇, 没发现有错误的地方, 整个完全按说明操作的,试遍了各种方法,都是卡在这步了

**Comment by xunichanghuan** [comment]
试试现在代码https://github.com/xunichanghuan/mimotion-run/tree/d137f755554543412444082efc233e7970bba296 ，一直在改代码，有可以你们fork的是有问题代码

**Comment by xunichanghuan** [comment]
最新代码配置CONFIG字段就行

**Comment by xunichanghuan** [comment]
> 最新代码配置CONFIG字段就行
>> 除 **MIMOTION** 字段外，其他字段按需配置
