### ISSUE TITLE
zfb你们能同步吗

### ISSUE THREAD

**Issue by lxhlemon** [xunichanghuan/mimotion-run#3]

**Comment by euzenlee** [comment]
> 不行。。。只有微信可以。。。支付宝自己把接口那边给断了

之前用手机号注册的账号还是可以同步的，只有最近新注册的email账号不行，不过恐怕那部分账号也会被断掉。

**Comment by zhangbo-sys** [comment]
> > 不行。。。只有微信可以。。。支付宝自己把接口那边给断了
> 
> 之前用手机号注册的账号还是可以同步的，只有最近新注册的email账号不行，不过恐怕那部分账号也会被断掉。

我的手机号注册的也不能同步

**Comment by euzenlee** [comment]
> > 之前用手机号注册的账号还是可以同步的，只有最近新注册的email账号不行，不过恐怕那部分账号也会被断掉。
> 
> 我的手机号注册的也不能同步
会不会是支付宝是按小米账号的注册时间线来处理，又或者账号触 发了什么条件，比如小米运动的账号曾经绑定过多个支付宝之类？

**Comment by xunichanghuan** [comment]
支付宝我的账号今天又能同步了

**Comment by euzenlee** [comment]
> 支付宝我的账号今天又能同步了

手机注册的，还是邮件注册的？

**Comment by Songpenglei123** [comment]
> > 不行。。。只有微信可以。。。支付宝自己把接口那边给断了
> 
> 之前用手机号注册的账号还是可以同步的，只有最近新注册的email账号不行，不过恐怕那部分账号也会被断掉。

微信也不行了
