### ISSUE TITLE
真是奇了怪

### ISSUE THREAD

**Issue by matocool** [xunichanghuan/mimotion-run#4]
作者自己的，https://github.com/xunichanghuan/mimotion-run/actions/runs/4281700322/jobs/7455047366

Successfully installed certifi-2022.12.7 charset-normalizer-3.0.1 idna-3.4 requests-2.28.2 urllib3-1.26.14
帐号信息: +861****1868
修改信息: success
修改步数: 59418
帐号信息: +861****1861
修改信息: success
修改步数: 28511
帐号信息: +861****14[32](https://github.com/xunichanghuan/mimotion-run/actions/runs/4281700322/jobs/7455047366#step:5:32)
修改信息: success
修改步数: 164
帐号信息: +861****[33](https://github.com/xunichanghuan/mimotion-run/actions/runs/4281700322/jobs/7455047366#step:5:33)59
修改信息: success
修改步数: 18210
帐号信息: +861****87[39](https://github.com/xunichanghuan/mimotion-run/actions/runs/4281700322/jobs/7455047366#step:5:39)
修改信息: success
修改步数: 121[40](https://github.com/xunichanghuan/mimotion-run/actions/runs/4281700322/jobs/7455047366#step:5:40)
帐号信息: 1065****.com
修改信息: success
修改步数: 25096

True
True
***"errcode":0,"errmsg":"ok","invalidparty":"NO","invalidtag":"0","msgid":"WpLDpQFMGSE8[43](https://github.com/xunichanghuan/mimotion-run/actions/runs/4281700322/jobs/7455047366#step:5:43)kRbNhgXdtU_PIOB-0nPKcBgavLrxejpaLzjKc4BY0jKm2VfDhQOp1kinX114myVsjjmqSyVQ"***

**Comment by xunichanghuan** [comment]
重新fork
