### ISSUE TITLE
我这边汇总下我知道的消息，做个分享。

### ISSUE THREAD

**Issue by matocool** [xunichanghuan/mimotion-run#5]
https://www.52pojie.cn/thread-1750173-1-1.html

https://motion.faithxy.com/

支付宝步数不同步

方法1、在支付宝设置-隐私-个人授权管理-取消对zepp Life的授权，然后注销zeppLIfe账号，重新绑定

方法2、在支付宝取消授权后，新注册一个zepp Life账号绑定，改步  

注：部分账号数据同步可能有延迟

注：建议在上午9点-晚上23点间修改步数，其它时间段步数可能不同步

本人亲测【方法2】，成功。

**Comment by zhangbo-sys** [comment]
重新注册了新账号还是不同步

**Comment by zhangbo-sys** [comment]
找了个手环连上就能正常同步了

**Comment by zhangbo-sys** [comment]
> > 找了个手环连上就能正常同步了
> 
> 但是很多人是没有手环的。。。。。我是先取消了支付宝授权，然后去把老账号解除了关联。重新注册了一个新的邮箱账号关联。就有效了。

我也是这样操作的，注册了两个新号都不同步，后来换回老号，连了个手环就可以同步

**Comment by euzenlee** [comment]
> 找了个手环连上就能正常同步了

我也怀疑是这个原因，有个手机的老号，是绑定了手环的，一直可以稳定同步。其他新注册的账号，没有绑定手环，开始成功三几天后，就一直没成功过。

**Comment by euzenlee** [comment]
> > 找了个手环连上就能正常同步了
> 
> 但是很多人是没有手环的。。。。。我是先取消了支付宝授权，然后去把老账号解除了关联。重新注册了一个新的邮箱账号关联。就有效了。

这个也关注一下，看后续是否可以稳定持久。我的新账号是最近才注册的，大概同步4，5天左右就掉了。

**Comment by euzenlee** [comment]
解绑支付宝，新注册zepp账号，绑定支付宝，改步数，这一套步骤做下来，还是不能同步到支付宝，上面成功的，估计还是另有其他因素。
