### ISSUE TITLE
fork最新的，运行报错

### ISSUE THREAD

**Issue by BIGMONK** [xunichanghuan/mimotion-run#6]
![1677661672428](https://user-images.githubusercontent.com/18308637/222093798-f9bbe480-054a-4840-87bf-e3f7c3ca6c5c.png)
'location'
cannot unpack non-iterable NoneType object

**Comment by BIGMONK** [comment]
> 目前除了作者本人，所有人的FORK我检查了都是报错

代码里面引用的变量是user，配置说明文件给的是phone，把phone改成user就好了

**Comment by xunichanghuan** [comment]
> > 目前除了作者本人，所有人的FORK我检查了都是报错
> 
> 代码里面引用的变量是user，配置说明文件给的是phone，把phone改成user就好了

疏忽🥹
